import "./globals.css";
import { Inter } from "next/font/google";
import NavBar from "@/components/NavBar";
import Image from "next/image";
import profilePicright from "public/right.png";
import profilePicleft from "public/left.png";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    //bg-[url("pic/right.png")]  bg-repeat-x bg-center top-0
    <html lang="en">
      <body
        className={`$inter.className bg-gradient-to-l from-blue-700 via-blue-900 to-blue-600  h-screen`}
      >
        <div className="relative container  mx-auto my-auto lg:mt-32   bg-white   	  ">
          <div className=" ">
            <div
              className="absolute flex  w-full h[30rem] z-10 "
            >
             
              <Image
              className="sm:block "
                src={profilePicleft}
                alt="Picture of the author"
                 width={160} 
               height={100} 
                // blurDataURL="data:..." automatically provided
                // placeholder="blur" // Optional blur-up while loading
              />
            </div>
         
            <div className="absolute lg:flex   w-full h-full z-10 hidden -pt-1 ">
            <Image
            className="absolute right-0"
              src={profilePicright}
              alt="Picture of the author"
              width={460} 
              height={460}
              // blurDataURL="data:..." automatically provided
              // placeholder="blur" // Optional blur-up while loading
            />
            </div>
          </div>
          <NavBar />
          {children}
        </div>
      </body>
    </html>
  );
}
