import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`$inter.className bg-gradient-to-r from-blue-800 to-indigo-900  h-screen`}>      
        <div className='container mx-auto my-auto lg:mt-32 border  bg-white '>
           {children}
           </div>        
        </body>
    </html>
  )
}
